name: Build docker image

on:
  create:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
#  build-vanilla:
#    if: ${{ startsWith(github.ref, 'refs/tags/') }}
#    runs-on: ubuntu-20.04
#
#    permissions:
#      contents: read
#      packages: write
#
#    strategy:
#      matrix:
#        go-version: [1.18.x]
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: ${{ matrix.go-version }}
#      - uses: actions/cache@v3
#        with:
#          path: |
#            ~/.cache/go-build
#            ~/go/pkg/mod
#          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-go-
#      - name: Build
#        run: go build -v -ldflags "-X main.Version=${{ github.event.ref }} -X main.Commit=${{ github.sha }}" -o ./sfeth ./cmd/sfeth
#      - name: Log in to the Container registry
#        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Generate docker tags/labels from github build context
#        id: meta
#        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#        with:
#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#          tags: |
#            type=ref,event=tag
#          flavor: latest=true
#      - name: Build and push Docker image
#        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}

  bundle-docker-versions:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        binary: [geth, bsc, polygon]
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker pull ghcr.io/streamingfast/go-ethereum:${{ matrix.binary }}-latest
          VERSION=$(docker inspect --format='{{index .Config.Labels \"org.opencontainers.image.version\"}}' ghcr.io/streamingfast/go-ethereum:geth-latest)
          echo VERSION=$VERSION >> $GITHUB_ENV
      - name: Generate docker tags/labels from github build context
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag,suffix=${{ env.VERSION }}
          flavor: latest=false
      - run: echo "${{ steps.meta.outputs.tags }}"

#      - name: Build and push Docker image
#        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
